services:
  postgres:
    image: postgres:16.10
    container_name: stray_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in .env}
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}

    ports:
      - "1234:1234"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: